name: Release

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: aquaproj/aqua-installer@v3.1.1
        with:
          aqua_version: v2.43.0
      - run: npm ci
      - run: npm run publish
        env:
          GITHUB_TOKEN: ${{ github.token }}
